### ISSUE TITLE
Doing all SnakeAnimations at once?

### ISSUE THREAD

**Issue by JonnyIrl** [IvanSanchez/Leaflet.Polyline.SnakeAnim#10]
Hi,

I'm just wondering if it's possible to do all snake animations at once.

I have a list of about 150 points, they all get populated on the map at the same time, what I would like is for them ALL to animate at the same time instead of 1 by 1 until they are all finished. They are all going towards the same end point, but different markers.

Thank you.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find this Leaflet plugin useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet or its plugins, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
