### ISSUE TITLE
Can I use it with leaflet-curve

### ISSUE THREAD

**Issue by maximusnikulin** [IvanSanchez/Leaflet.Polyline.SnakeAnim#16]
I have task to draw animated path. I use leaflet-curve and it works, but without animation. Now I find a way to animate it. May you help me with it?

**Comment by IvanSanchez** [comment]
This issue tracker is used for reporting bugs. I do not have the time to implement new features on request.

Read the code for SnakeAnim, understand how it works, read leaflet-curve's code. Understand how they work and whether they could or could not work together.

Once you have **specific**, **technical** bugs or requests, say so.

If you have the time, I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["http://www.chiark.greenend.org.uk/~sgtatham/bugs.html"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html). It will help you understand why I'm protective about how I spend my time and efforts.
