### ISSUE TITLE
why can't it work with Leaflet 0.7.x as well?

### ISSUE THREAD

**Issue by wandergis** [IvanSanchez/Leaflet.Polyline.SnakeAnim#2]
If i use leaflet0.7.x,it tells me that **Uncaught TypeError: Cannot set property 'snakingPause' of undefined**，so I want to know how can i let it work well with leaflet0.7.x

**Comment by IvanSanchez** [comment]
> why can't it work with Leaflet 0.7.x as well?

Because I don't want to maintain two versions.

Adapting the code for 0.7.x involves branching for `L.Polyline` and `L.MultiPolyline`, among other stuff. I don't use 0.7.x anymore (I'm focusing on fixing bugs on Leaflet 1.0.0 betas), so I have no real incentive to adapt the code.
