### ISSUE TITLE
Can't get the animation working. (No errors in the console)

### ISSUE THREAD

**Issue by bhupinders** [IvanSanchez/Leaflet.Polyline.SnakeAnim#40]
I just cloned the repo and was trying to run it. I get the whole route on the map immediately. Is there any other requirement I am missing? I don't see any errors also in the console. (Tried chrome/firefox both)

**Comment by IvanSanchez** [comment]
Did you press the button?

**Comment by bhupinders** [comment]
Thanks a lot. That was a really dumb mistake. The button wasn't visible on my smaller screen and I didn't look for it. We can close this.
