### ISSUE TITLE
snakingSpeed not work

### ISSUE THREAD

**Issue by jxiaox** [IvanSanchez/Leaflet.Polyline.SnakeAnim#6]
var route = L.layerGroup([
    L.marker(airport1),
    L.polyline([airport1, airport2]),
    L.marker(airport2)
], { snakingSpeed: 500 });
route.addTo(map).snakeIn();

**Comment by IvanSanchez** [comment]
Not a good bug report. Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
